#################################################
# Configuracao GeoServer: PRD
#################################################
---
- hosts: geoserverprimary

  tasks:
    - name: Instalar repositorio EPEL
      become: yes
      yum:
        name:
          - epel-release
        state: present

    - name: Atualizar pacotes base
      become: yes
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Instalar pacotes padroes
      become: yes
      yum:
        name:
          - vim
          - wget
          - curl
          - git
        state: present

    - name: Instalar Java 11
      become: yes
      yum:
        name:
          - java-11-openjdk-devel
        state: present
    
    - name: Copiar JAI & ImageIO
      become: yes
      copy:
        src: "files/jai/"
        dest: "/usr/lib/jvm/java-11-openjdk"
        mode: 0755

    - name: Instalar JAI & ImageIO
      become: yes
      shell: >
        tail -n +139 jai-1_1_3-lib-linux-amd64-jdk.bin > INSTALL-jai
        && chmod u+x INSTALL-jai
        && ./INSTALL-jai
        && rm jai-1_1_3-lib-linux-amd64-jdk.bin INSTALL-jai *.txt
        && tail -n +215 jai_imageio-1_1-lib-linux-amd64-jdk.bin > INSTALL-jai_imageio
        && chmod u+x INSTALL-jai_imageio
        && ./INSTALL-jai_imageio
        && rm jai_imageio-1_1-lib-linux-amd64-jdk.bin INSTALL-jai_imageio *.txt
      args:
        chdir: "/usr/lib/jvm/java-11-openjdk"

    - name: Criar grupo GeoServer
      become: yes
      group:
        name: geoserver
    
    - name: Criar usuario geoserver
      become: yes
      user:
        name: geoserver
        group: geoserver
        home: "/usr/share/geoserver"
        createhome: no

    - name: Criar diretorio GEOSERVER_HOME
      become: yes
      file:
        path: "{{ geoserver_home }}"
        state: directory
        mode: 0755

    - name: Criar diretorio GEOWEBCACHE_CACHE_DIR
      become: yes
      file:
        path: "{{ geoserver_geowebcache }}"
        state: directory
        mode: 0755

    - name: Criar diretorio GEOSERVER_LOG_LOCATION
      become: yes
      file:
        path: "{{ geoserver_log_location }}"
        state: directory
        mode: 0755

    - name: Copiar GEOSERVER_DATA_DIR
      become: yes
      copy:
        src: "files/data_dir.tar.gz"
        dest: "/tmp/data_dir.tar.gz"
        mode: 0755

    - name: Descompactar GEOSERVER_DATA_DIR
      become: yes
      unarchive:
        src: "/tmp/data_dir.tar.gz"
        dest: "{{ geoserver_shared }}"
        remote_src: yes

    - name: Copiar configuracoes de controlflow
      become: yes
      copy:
        src: "files/controlflow.properties"
        dest: "{{ geoserver_data_dir }}"
        mode: 0755

    - name: Copiar GeoServer
      become: yes
      copy:
        src: "files/geoserver.tar.gz"
        dest: "/tmp/geoserver.tar.gz"
        mode: 0755

    - name: Descompactar GeoServer
      become: yes
      unarchive:
        src: "/tmp/geoserver.tar.gz"
        dest: "{{ geoserver_home }}"
        extra_opts: [--strip-components=1]
        remote_src: yes

    - name: Copiar configuracoes de log
      become: yes
      copy:
        src: "files/log4j.properties"
        dest: "{{ geoserver_home }}/resources/log4j.properties"
        mode: 0755

    - name: Copiar web.xml
      become: yes
      template:
        src: "templates/web.xml.j2"
        dest: "{{ geoserver_home }}/webapps/geoserver/WEB-INF/web.xml"

    - name: Copiar start.ini
      become: yes
      template:
        src: "templates/start.ini.j2"
        dest: "{{ geoserver_home }}/start.ini"

    - name: Copiar startup.sh
      become: yes
      template:
        src: "templates/startup.sh.j2"
        dest: "{{ geoserver_home }}/bin/startup.sh"

    - name: Alterar ownership diretorios de dados GeoServer
      become: yes
      file:
        path: "{{ geoserver_shared }}"
        owner: geoserver
        group: geoserver
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Alterar ownership diretorios de instalacao GeoServer
      become: yes
      file:
        path: "{{ geoserver_home }}"
        owner: geoserver
        group: geoserver
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copiar geoserver service da maquina local para servidor
      become: yes
      template:
        src: "templates/geoserver.service.j2"
        dest: "/etc/systemd/system/geoserverprimary.service"

    - name: Habilitar geoserver service
      become: yes
      systemd:
        name: geoserverprimary
        state: started
        enabled: true
        daemon_reload: true
