#################################################
# Configuracao GeoServer: PRD
#################################################
---
- hosts: all
  tasks:
    - name: Instalar repositorio EPEL
      become: yes
      yum:
        name:
          - epel-release
        state: present

    - name: Atualizar pacotes base
      become: yes
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Instalar pacotes padroes
      become: yes
      yum:
        name:
          - vim
          - wget
          - curl
          - git
        state: present

    - name: Instalar Java 11
      become: yes
      yum:
        name:
          - java-11-openjdk-devel
        state: present
    
    - name: Copiar JAI & ImageIO
      become: yes
      copy:
        src: "files/jai/"
        dest: "/usr/lib/jvm/java-11-openjdk"
        mode: 0755

    - name: Instalar JAI & ImageIO
      become: yes
      shell: >
        tail -n +139 jai-1_1_3-lib-linux-amd64-jdk.bin > INSTALL-jai
        && chmod u+x INSTALL-jai
        && ./INSTALL-jai
        && rm jai-1_1_3-lib-linux-amd64-jdk.bin INSTALL-jai *.txt
        && tail -n +215 jai_imageio-1_1-lib-linux-amd64-jdk.bin > INSTALL-jai_imageio
        && chmod u+x INSTALL-jai_imageio
        && ./INSTALL-jai_imageio
        && rm jai_imageio-1_1-lib-linux-amd64-jdk.bin INSTALL-jai_imageio *.txt
      args:
        chdir: "/usr/lib/jvm/java-11-openjdk"

    - name: Criar grupo GeoServer
      become: yes
      group:
        name: geoserver
    
    - name: Criar usuario geoserver
      become: yes
      user:
        name: geoserver
        group: geoserver
        home: "/usr/share/geoserver"
        createhome: no

    - name: Instalar NGINX
      become: yes
      yum:
        name:
          - nginx
        state: present

    - name: Backup nginx.conf
      become: yes
      copy:
        src: "/etc/nginx/nginx.conf"
        dest: "/etc/nginx/backup.nginx.conf"
        remote_src: yes

    - name: Habilitar nginx service
      become: yes
      systemd:
        name: nginx
        state: started
        enabled: true
        daemon_reload: true

    - name: Configurar CentOS para possibilitar proxy_pass upstream
      become: yes
      command: setsebool -P httpd_can_network_connect 1
      ignore_errors: yes

    - name: Criar diretorio logs NGINX
      become: yes
      file:
        path: "{{ nginx_log_location }}"
        state: directory
        mode: 0755

    - name: Instalar Rsync
      become: yes
      yum:
        name:
          - rsync
        state: present

    - name: Criar diretorio Rsync
      become: yes
      file:
        path: "{{ rsync_config }}"
        state: directory
        mode: 0755


- hosts: geoserverprimary
  handlers:
    - name: restart nginx
      become: yes
      systemd:
        name: nginx
        state: restarted
  tasks:
    - name: Criar diretorio GEOSERVER_HOME
      become: yes
      file:
        path: "{{ primary_geoserver_home }}"
        state: directory
        mode: 0755

    - name: Criar diretorio GEOWEBCACHE_CACHE_DIR
      become: yes
      file:
        path: "{{ primary_geoserver_geowebcache }}"
        state: directory
        mode: 0755

    - name: Criar diretorio GEOSERVER_LOG_LOCATION
      become: yes
      file:
        path: "{{ primary_geoserver_log_location }}"
        state: directory
        mode: 0755

    - name: Copiar GEOSERVER_DATA_DIR
      become: yes
      copy:
        src: "files/data_dir.tar.gz"
        dest: "/tmp/data_dir.tar.gz"
        mode: 0755

    - name: Descompactar GEOSERVER_DATA_DIR
      become: yes
      unarchive:
        src: "/tmp/data_dir.tar.gz"
        dest: "{{ primary_geoserver_shared }}"
        remote_src: yes

    - name: Copiar configuracoes de controlflow
      become: yes
      copy:
        src: "files/controlflow.properties"
        dest: "{{ primary_geoserver_data_dir }}"
        mode: 0755

    - name: Copiar GeoServer
      become: yes
      copy:
        src: "files/geoserver.tar.gz"
        dest: "/tmp/geoserver.tar.gz"
        mode: 0755

    - name: Descompactar GeoServer
      become: yes
      unarchive:
        src: "/tmp/geoserver.tar.gz"
        dest: "{{ primary_geoserver_home }}"
        extra_opts: [--strip-components=1]
        remote_src: yes

    - name: Copiar configuracoes de log
      become: yes
      copy:
        src: "files/log4j.properties"
        dest: "{{ primary_geoserver_home }}/resources/log4j.properties"
        mode: 0755

    - name: Copiar web.xml
      become: yes
      template:
        src: "templates/cluster/primary/web.xml.j2"
        dest: "{{ primary_geoserver_home }}/webapps/geoserver/WEB-INF/web.xml"

    - name: Copiar start.ini
      become: yes
      template:
        src: "templates/cluster/primary/start.ini.j2"
        dest: "{{ primary_geoserver_home }}/start.ini"

    - name: Copiar startup.sh
      become: yes
      template:
        src: "templates/cluster/primary/startup.sh.j2"
        dest: "{{ primary_geoserver_home }}/bin/startup.sh"

    - name: Alterar ownership diretorios de dados GeoServer
      become: yes
      file:
        path: "{{ primary_geoserver_shared }}"
        owner: geoserver
        group: geoserver
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Alterar ownership diretorios de instalacao GeoServer
      become: yes
      file:
        path: "{{ primary_geoserver_home }}"
        owner: geoserver
        group: geoserver
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copiar geoserver service da maquina local para servidor
      become: yes
      template:
        src: "templates/cluster/primary/geoserver.service.j2"
        dest: "/etc/systemd/system/geoserverprimary.service"

    - name: Habilitar geoserver service
      become: yes
      systemd:
        name: geoserverprimary
        state: started
        enabled: true
        daemon_reload: true

    - name: Copiar configuracao NGINX
      become: yes
      template:
        src: "templates/cluster/primary/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
      notify:
        - restart nginx

    - name: Copiar chave SSH Rsync
      become: yes
      copy:
        src: "keys/rsync/rsync_key.pub"
        dest: "{{ rsync_config }}"
        mode: 0755

    - name: Alterar ownership diretorios Rsync
      become: yes
      file:
        path: "{{ rsync_config }}"
        owner: geoserver
        group: geoserver
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Add rsync_key.pub em /root/.ssh/authorized_keys
      become: yes
      shell: >
        mkdir -p /root/.ssh
        && chmod 700 /root/.ssh
        && touch /root/.ssh/authorized_keys
        && chmod 600 /root/.ssh/authorized_keys
        && cat {{ rsync_config }}/rsync_key.pub >> /root/.ssh/authorized_keys


- hosts: geoserversecundary
  handlers:
    - name: restart nginx
      become: yes
      systemd:
        name: nginx
        state: restarted
  tasks:
    - name: Criar diretorio GEOSERVER_HOME
      become: yes
      file:
        path: "{{ secundary_geoserver_home }}_{{ item }}"
        state: directory
        mode: 0755
      with_items: "{{ secundary_geoserver_nodes_jetty_ports }}"

    - name: Criar diretorio GEOWEBCACHE_CACHE_DIR
      become: yes
      file:
        path: "{{ secundary_geoserver_geowebcache }}"
        state: directory
        mode: 0755

    - name: Criar diretorio GEOSERVER_LOG_LOCATION
      become: yes
      file:
        path: "{{ secundary_geoserver_log_location }}"
        state: directory
        mode: 0755

    - name: Copiar GEOSERVER_DATA_DIR
      become: yes
      copy:
        src: "files/data_dir.tar.gz"
        dest: "/tmp/data_dir.tar.gz"
        mode: 0755

    - name: Descompactar GEOSERVER_DATA_DIR
      become: yes
      unarchive:
        src: "/tmp/data_dir.tar.gz"
        dest: "{{ secundary_geoserver_shared }}"
        remote_src: yes

    - name: Copiar configuracoes de controlflow
      become: yes
      copy:
        src: "files/controlflow.properties"
        dest: "{{ secundary_geoserver_data_dir }}"
        mode: 0755

    - name: Copiar GeoServer
      become: yes
      copy:
        src: "files/geoserver.tar.gz"
        dest: "/tmp/geoserver.tar.gz"
        mode: 0755

    - name: Descompactar GeoServer
      become: yes
      unarchive:
        src: "/tmp/geoserver.tar.gz"
        dest: "{{ secundary_geoserver_home }}_{{ item }}"
        extra_opts: [--strip-components=1]
        remote_src: yes
      with_items: "{{ secundary_geoserver_nodes_jetty_ports }}"

    - name: Copiar configuracoes de log
      become: yes
      copy:
        src: "files/log4j.properties"
        dest: "{{ secundary_geoserver_home }}_{{ item }}/resources/log4j.properties"
        mode: 0755
      with_items: "{{ secundary_geoserver_nodes_jetty_ports }}"

    - name: Copiar web.xml
      become: yes
      template:
        src: "templates/cluster/secundary/web.xml.j2"
        dest: "{{ secundary_geoserver_home }}_{{ item }}/webapps/geoserver/WEB-INF/web.xml"
      with_items: "{{ secundary_geoserver_nodes_jetty_ports }}"

    - name: Copiar start.ini
      become: yes
      template:
        src: "templates/cluster/secundary/start.ini.j2"
        dest: "{{ secundary_geoserver_home }}_{{ item }}/start.ini"
      with_items: "{{ secundary_geoserver_nodes_jetty_ports }}"

    - name: Copiar startup.sh
      become: yes
      template:
        src: "templates/cluster/secundary/startup.sh.j2"
        dest: "{{ secundary_geoserver_home }}_{{ item }}/bin/startup.sh"
      with_items: "{{ secundary_geoserver_nodes_jetty_ports }}"

    - name: Alterar ownership diretorios de dados GeoServer
      become: yes
      file:
        path: "{{ secundary_geoserver_shared }}"
        owner: geoserver
        group: geoserver
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Alterar ownership diretorios de instalacao GeoServer
      become: yes
      file:
        path: "{{ secundary_geoserver_home }}_{{ item }}"
        owner: geoserver
        group: geoserver
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
      with_items: "{{ secundary_geoserver_nodes_jetty_ports }}"

    - name: Copiar geoserver service da maquina local para servidor
      become: yes
      template:
        src: "templates/cluster/secundary/geoserver.service.j2"
        dest: "/etc/systemd/system/geoserversecundary_{{ item }}.service"
      with_items: "{{ secundary_geoserver_nodes_jetty_ports }}"

    - name: Habilitar geoserver service
      become: yes
      systemd:
        name: "geoserversecundary_{{ item }}"
        state: started
        enabled: true
        daemon_reload: true
      with_items: "{{ secundary_geoserver_nodes_jetty_ports }}"

    - name: Copiar configuracao NGINX
      become: yes
      template:
        src: "templates/cluster/secundary/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
      notify:
        - restart nginx

    - name: Copiar chave SSH Rsync
      become: yes
      copy:
        src: "keys/rsync/rsync_key"
        dest: "{{ rsync_config }}"
        mode: 0755

    - name: Copiar script bash para rodar crontab Rsync
      become: yes
      template:
        src: "templates/cluster/secundary/crontab_sync_data_dir.sh.j2"
        dest: "{{ rsync_config }}/crontab_sync_data_dir.sh"

    - name: Alterar ownership diretorios Rsync
      become: yes
      file:
        path: "{{ rsync_config }}"
        owner: geoserver
        group: geoserver
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Add crontab para sincronizar pastas */30 * * * * (a cada 30 minutos)"
      become: yes
      shell: >
        echo "*/30 * * * * root bash {{ rsync_config }}/crontab_sync_data_dir.sh" >> /etc/crontab
